name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Spring Boot app
        run: |
          cd spring-app
          mvn clean package -DskipTests

      - name: Run Spring Boot unit tests
        run: |
          cd spring-app
          mvn test

      - name: Build and start Docker Compose stack
        run: |
          docker-compose up -d
          # Даем сервисам время на старт
          sleep 30

      - name: Check custom metric in Prometheus
        run: |
          # Ждем, пока сервисы полностью стартуют (можно увеличить паузу при необходимости)
          for i in {1..12}; do
            if curl -s http://localhost:9090/api/v1/query?query=custom_random_metric | grep -q '"status":"success"'; then
              echo "custom_random_metric found!"
              exit 0
            else
              echo "Waiting for metric... ($i)"
              sleep 5
            fi
          done
          echo "custom_random_metric not found!"
          exit 1

      - name: Shutdown Docker Compose
        if: always()
        run: docker-compose down
